ben-pister.WebUI/Models/Eatery_Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.UI.HtmlControls;
using ben_pister.Domain.Entities;
using System.IO;
using System.Web.Mvc;

namespace ben_pister.WebUI.Models
{
    public class Eatery_Repository
    {
        public string cheddarsMenu;

        private List<KentuckianaEats> Restaurants = new List<KentuckianaEats>();

        public Eatery_Repository()
        {
            
        }

        public List<KentuckianaEats> populateEats()
        {
            string line = "";
            string[] array = new string[4];
            char[] splitter = { '|' };
            KentuckianaEats ke;

            var root = AppDomain.CurrentDomain.BaseDirectory;

            StreamReader file = new StreamReader(root + @"/Doc_Resources/KentuckianaEats.txt");

            while ((line = file.ReadLine()) != null)
            {
                array = line.Split(splitter);

                ke = new KentuckianaEats();

                if (array.Length == 5)
                {
                    ke.Name = array[0];
                    ke.Location = array[1];
                    ke.Phone = array[2];
                    ke.ExpenseLevel = array[3];

                    TagBuilder tag = new TagBuilder("a");
                    tag.MergeAttribute("href", array[4].Trim());
                    tag.MergeAttribute("target", "blank");
                    tag.InnerHtml = "Menu";                    
                    ke.MenuWebSite = MvcHtmlString.Create(tag.ToString());

                    Restaurants.Add(ke);
                }
            }

            List<KentuckianaEats> sortedRest = Restaurants.OrderBy(o => o.Name).ToList<KentuckianaEats>();

            return sortedRest;
        }
    }
}

ben-pister.WebUI/Models/MathGameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ben_pister.WebUI.Models
{
    public class MathGameViewModel
    {
        public int Time { get; set; }
        public int Score { get; set; }
        public int Level { get; set; }

        public int LevelTwoMultiple { get; } = 10;

        public int LevelThreeMultiple { get; } = 15;

        public MathGameViewModel() { }
    }
}

ben-pister.WebUI/Controllers/FileDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ben_pister.WebUI.Controllers
{
    public class FileDownloadController : Controller
    {
        // GET: FileDownload
        public ActionResult PdfDownload()
        {
            
            return File("~/Doc_Resources/Ben Pister Resume_1.pdf", "application/pdf", "Ben Pisters Resume.pdf");
        }
    }
}

ben-pister.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ben_pister.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                throw new Exception();
            }

        }
    }
}

ben-pister.WebUI/Controllers/Interesting_InfoController.cs
using ben_pister.WebUI.Models;
using System.Web.Mvc;

namespace ben_pister.WebUI.Controllers
{
    public class Interesting_InfoController : Controller
    {
        // GET: Hobbies
        public ActionResult Hobbies()
        {
            //Eatery_Repository er = new Eatery_Repository();

            return View();
        }
    }
}

ben-pister.WebUI/Controllers/KentuckianaEatsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ben_pister.WebUI.Models;
using ben_pister.Domain.Entities;

namespace ben_pister.WebUI.Controllers
{
    public class KentuckianaEatsController : Controller
    {
        List<KentuckianaEats> ke = new List<KentuckianaEats>();
        // GET: KentuckianaEats
        public ActionResult KIEats()
        {
            Eatery_Repository er = new Eatery_Repository();

            //ViewBag.KEList = er.populateEats();

            return View(er.populateEats());
        }
    }
}

ben-pister.WebUI/Controllers/MathChallengeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ben_pister.WebUI.Controllers
{
    public class MathChallengeController : Controller
    {
        // GET: InformationEntry
        public ActionResult HandleInformation()
        {
            return View();
        }
    }
}

ben-pister.WebUI/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ben_pister.WebUI.Controllers
{
    public class ResumeController : Controller
    {
        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }
    }
}

ben-pister.WebUI/Views/FileDownload/PdfDownload.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PdfDownload</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

ben-pister.WebUI/Views/Home/Analytics.cshtml
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87362496-1', 'auto');
  ga('send', 'pageview');

</script>

ben-pister.WebUI/Views/Home/FooterView.cshtml
<div class="foregnd">
    Ben is a very motivated, eager to learn developer currently working with the .NET platform
</div>

ben-pister.WebUI/Views/Home/Index.cshtml
@model string
<head>
    <link href="~/Content/HomeLayout.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/Doc_View.js"></script>
</head>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="visible-lg hidden-xs hidden-sm hidden-md bck_img"></div>
    <div class="hidden-lg bck_img_small"></div>
    <br />
    
    <div class="col-md-3 card-background" style="height:400px">
        <h5 class="my_header" style="color:teal">About Ben Pister</h5>
        <div class="message-font" style="color:teal">
            I am a software developer in the Louisville, KY region.
            <br />
            I have completed internships in Web Development with Oasis Technologies Group and ZirMed, 
            both of which are medical software companies in Louisville, KY.
            I also worked as a Software Development contractor for an additional 15 months.
        </div>
    </div>
</div>
    


<br /><br /><br /><br />







ben-pister.WebUI/Views/InformationEntry/HandleInformation.cshtml

@{
    ViewBag.Title = "HandleInformation";
}
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="~/Scripts/Doc_View.js"></script>
</head>

<div class="row">
    <div class="col-md-12">
        <h4>
            I enjoy working math problems in my head for exercise, an idea inspired by two math instructors:<br />
            a junior high math instructor and my high school calculus instructor.
        </h4>

        <span class="text-info">This will likely be a continually evolving work.<br /> I love math-based games of various kinds.</span>
    </div>
</div>

<body id="arithmeticBodyId" style="background-color:lightgrey">
    <div class="row">
        <div class="col-lg-5 col-md-6 col-xs-12 pad-top-10 text-center">
            <button id="gameInstructions">Show Game Play Instructions</button><br />
            <table id="gamePlayInstructions" class="table-responsive table-bordered table-striped level-instruction-table" style="display:none">
                <thead>
                    <tr>
                        <td><strong>Game Play Instructions</strong></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            The goal of this "game" is for individuals to solve as many math problems as possible in 5 minutes (300 seconds).<br />
                            It is, of course, not possible to restrict calculators but I do encourage people to challenge themselves
                            to use their great built-in computer, the human brain (on paper if needed, of course). <br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Once a level is selected, this will be the level for the duration of the 5 minutes. <br />
                            If another level is desired, there is a "Reset Game" button at the bottom of the page.<br />
                            I have attempted to adjust scoring to the difficulty level of both level selection and 
                            mathematical operation selected.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>When a game has ended, click or tap the "Reset Game" button to start a new game.</strong>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>
                            Three consecutive incorrect answers on one problem results in a 5 point score reduction with a minimum score of 0.<br />
                            In this event, a calculation mode must be selected for another problem.
                        </td>
                    </tr>
                </tfoot>
            </table>

        </div>

        <div class="col-lg-7 col-md-6 col-xs-12 pad-top-10 text-center">
            <button id="showLevelInstructions">Show Level Selection Instructions</button><br />
            <table id="levelSelectionInstructions" class="table-responsive table-bordered table-striped level-instruction-table" style="display:none">
                <thead>
                    <tr>
                        <td></td>
                        <td>Addition / Subtraction</td>
                        <td>Multiplication</td>
                        <td>Division</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>L1</td>
                        <td>10 pts</td>
                        <td>100 pts</td>
                        <td>200 pts</td>
                    </tr>
                    <tr>
                        <td>L2</td>
                        <td>100 pts</td>
                        <td>@(100 * 10) pts</td>
                        <td>@(200 * 10) pts</td>
                    </tr>
                    <tr>
                        <td>L3</td>
                        <td>150 pts</td>
                        <td>@(100 * 15) pts</td>
                        <td>@(200 * 15) pts</td>
                    </tr>

                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            Three consecutive incorrect answers on one problem results in a 5 point score reduction with a minimum score of 0.<br />
                            In this event, a calculation mode must be selected for another problem.
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-5 col-md-6 col-xs-12 pad-top-75">
            <fieldset>
                <legend>Difficulty Level</legend>
                <div class="col-md-12">
                    <div class="col-md-2 pad-top-25">
                        <button id="btnL1" class="btn btn-default level-buttons">L1</button>
                    </div>
                    <div class="col-md-2 pad-top-25">
                        <button id="btnL2" class="btn btn-success level-buttons">L2</button>
                    </div>
                    <div class="col-md-2 pad-top-25">
                        <button id="btnL3" class="btn btn-danger level-buttons">L3</button>
                    </div>
                    <div class="col-md-6 col-xs-12">
                        @Html.Label("Selected Level", "Selected Level")<div class="clearfix"></div>
                        @Html.TextBox("levelSelected", "", new { @id = "levelSelected", @readonly="readonly", @class = "pad-bottom-10" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="col-lg-7 col-md-6 col-xs-12 pad-top-75 hidden-xs">
            <button id="btnKeyBoardShortcuts" class="pad-bottom-10">Show KeyBoard Shortcuts</button><br />
            <table id="keyBoardShortcutTable" class="table-responsive table-bordered table-striped col-xs-12" style="display:none">
                <thead>
                    <tr>
                        <td class="keyboard-shortcuts-header">Level 1</td>
                        <td class="keyboard-shortcuts-header">Level 2</td>
                        <td class="keyboard-shortcuts-header">Level 3</td>
                        <td class="keyboard-shortcuts-header">Add</td>
                        <td class="keyboard-shortcuts-header">Subtract</td>
                        <td class="keyboard-shortcuts-header">Multiply</td>
                        <td class="keyboard-shortcuts-header">Divide</td>
                        <td class="keyboard-shortcuts-header">Reset Game</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>ALT + 1</td>
                        <td>ALT + 2</td>
                        <td>ALT + 3</td>
                        <td>ALT + =</td>
                        <td>ALT + -</td>
                        <td>ALT + x</td>
                        <td>ALT + /</td>
                        <td>CTRL + r</td>
                    </tr>
                </tbody>
            </table>
        </div>
        

    </div>
    <br /><br />
    <div class="row">
        <div class="col-lg-3 col-md-4 col-xs-12">
            <div class="row text-left">
                <div class="col-md-8 col-xs-12">
                    @Html.Label("timerRemaining", "timeRemaining", new { @class = "text-left" })
                    @Html.TextBox("txtCountdown", "", new { @id = "txtCountdown", @readonly="readonly", @class="form-control pad-bottom-20" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-4 col-xs-12">
            <div class="row text-left">
                <div class="col-md-8 col-xs-12">
                    @Html.Label("Score", "Score", new { @class = "text-left" })
                    @Html.TextBox("txtScore", "0", new { @id = "txtScore", @readonly = "readonly", @class = "form-control pad-bottom-20" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 text-center">
            <div class="row">
                <div class="col-md-4 col-xs-6 arithmetic_btn">
                    <button id="btnAddition" class="btn btn-add btn-operation">
                        +<span id="addShortcut" class="pad-left-5 hidden-lg hidden-md hidden-sm hidden-xs shortcut-color" style="display:none">(ALT + =)</span>
                    </button>
                    <span id="mode_a"></span>
                </div>

                <div class="col-md-4 col-xs-6 arithmetic_btn">
                    <button id="btnSubtraction" class="btn btn-sub btn-operation">
                        --<span id="subtractShortcut" class="pad-left-5 hidden-lg hidden-md hidden-sm hidden-xs shortcut-color" style="display:none">(ALT + -)</span>
                    </button>
                    <span id="mode_s"></span>
                </div>
                <span id="mode_update"></span>

                <div class="clearfix"></div>

                <div class="col-md-4 col-xs-6 arithmetic_btn">
                    <button id="btnMultiplication" class="btn btn-mul btn-operation">
                        x<span id="multiplyShortcut" class="pad-left-5 hidden-lg hidden-md hidden-sm hidden-xs shortcut-color" style="display:none">(ALT + x)</span>
                    </button>
                    <span id="mode_m"></span>
                </div>

                <div class="col-md-4 col-xs-6 arithmetic_btn">
                    <button id="btnDivision" class="btn btn-div btn-operation">
                        /<span id="divideShortcut" class="pad-left-5 hidden-lg hidden-md hidden-sm  hidden-xs shortcut-color" style="display:none">(ALT + /)</span>
                    </button>
                    <span id="mode_d"></span>
                </div>
                <div class="clearfix"></div>

                <div class="col-md-8 arithmetic_btn">
                    <button id="btnResetGame" class="btn btn-default">
                        Reset Game<span id="resetShortcut" class="pad-left-5" style="display:none">(CTRL + r)</span>
                    </button>
                    <span id="resetStatusMessage"></span>
                </div>
                
                <div id="selectedModeFeedback" style="display:none">

                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-4 text-left">
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-3 sign-align">
                    <br />
                    <span id="arithmeticSign" class="arithmeticWeight"></span>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-4 arithmeticWeight">
                    <span id="num1" class="right-align"></span>
                    <br />
                    <span id="num2" class="right-align underline"></span>
                </div>
            </div>
            <div class="clearfix"></div>


            <div class="col-md-8">
                <label id="lblAnswer" class="label-space">Your Answer<span id="timeIsLow"></span></label>
                @Html.TextBox("answer", null, new { @class = "form-control", @type="number" })
            </div>

            <div class="col-md-8 message-pad-top">
                <span id="result-message"></span>
                <div id="mobileScoreUpdate" class="hidden-lg hidden-md visible-xs"></div>
            </div>
            <br />
            <div class="col-md-8">
                <button id="btnSubmitAnswer" class="btn btn-primary">Submit Answer</button>
            </div>

            <div class="clearfix"></div>
            <br /><br /><br /><br /><br />

            <div class="col-md-8" style="display:none">
                <label class="label-space">Number 1</label>
                @Html.TextBox("txtNum1", null, new { @class = "hidden-control", @readonly = "readonly" })
            </div>

            <div class="col-md-8" style="display:none">
                <label class="label-space">Number 2</label>
                @Html.TextBox("txtNum2", null, new { @class = "hidden-control", @readonly = "readonly" })
            </div>

            <div style="display:none">
                @Html.TextBox("txt-mode", null, new { @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("correct-answer", "", new { @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("submitStatus", "0", new { @id = "submitStatus", @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("numbersGenerated", "0", new { @id = "numbersGenerated", @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("attempts", "0", new { @id = "attempts", @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("txtBoundary", "", new { @class = "hidden-control" })
            </div>

            <div style="display:none">
                @Html.TextBox("txtMin", "", new { @class = "hidden-control" })
            </div>
        </div>
    </div>
    <br /><br /><br />
</body>

ben-pister.WebUI/Views/Interesting_Info/Eateries.cshtml
@model ben_pister.WebUI.Models.Eatery_Repository

@{
    ViewBag.Title = "Eateries";
}

<div >
    
</div>

ben-pister.WebUI/Views/Interesting_Info/Hobbies.cshtml


@{
    ViewBag.Title = "Hobbies";
}

<div class="bck_img_photo_hobby">

</div>
<h2 class="text-center font-700">Hobbies</h2>

<div class="row table-bordered card-gray">
    <div class="card-gray"></div>
    <div class="col-md-6" style="border-right:2px solid white;background-color:#e3e1df;opacity:0.6;height:440px">
        <h4 class="text-center my_header">Indoor</h4>
        <br />
        <div class="pad-left-20 message-font">Programming Languages</div>
        <ul>
            <li class="pad-left-100 message-font"><strong>C#</strong></li>
            <li class="pad-left-100 message-font">JavaScript</li>
            <li class="pad-left-100 message-font">CSS</li>
            <li class="pad-left-100 message-font">HTML</li>
            <li class="pad-left-100 message-font">SQL</li>
            <li class="pad-left-100 message-font">Java</li>
            <li class="pad-left-100 message-font">Scala</li>
            <li class="pad-left-100 message-font">C++</li>
            <li class="pad-left-100 message-font">Visual Basic</li>
        </ul>
    </div>

    <div class="col-md-6" style="background-color:#e3e1df;opacity:0.6;height:440px">
        <h4 class="text-center my_header">Outdoor</h4>
        <br />
        <div class="pad-left-20 message-font">Hiking</div>
            <ul>
                <li class="pad-left-100 message-font">Adirondacks (New York)</li>
                <li class="pad-left-100 message-font">Presidential Range (New Hampshire)</li>
                <li class="pad-left-100 message-font">Red River Gorge (Eastern KY)</li>
                <li class="pad-left-100 message-font">Brown County State Park (Brown County, IN)</li>
                <li class="pad-left-100 message-font">Harrison Crawford Forest (Harrison/Crawford Counties, IN)</li>
            </ul>
        
        <div class="pad-left-20 message-font">Photography</div>
            <ul>
                <li class="pad-left-100 message-font">Outdoor photography is one of my releases and actually had much to do with 
                how I transitioned into software development.  My photography locations are anywhere I hike.</li>
            </ul>
    </div>
</div>

<div class="row" style="background-color:#e3e1df;opacity:0.6;height:300px">
    <div class="col-md-12 table-bordered min-height-100"><div class="pad-left-20 my_header">Development Projects</div></div>
    <ul>
        <li class="pad-left-100 message-font">C# Web Project - developed to allow food truck vendors to track locations and monitor success.</li>
        <li class="pad-left-100 message-font">SQL Server Management Studio database development</li>
        <li class="pad-left-100 message-font">C# Windows forms</li>
        <li class="pad-left-100 message-font">Java search algorithm projects</li>
        <li class="pad-left-100 message-font">MySQL Database development</li>
    </ul>
</div>

<br /><br /><br />




ben-pister.WebUI/Views/KentuckianaEats/KIEats.cshtml
@using ben_pister.Domain.Entities
@model List<KentuckianaEats>

@{
    ViewBag.Title = "KIEats";
    
}

<head>
    @Styles.Render("~/Content/css")
</head>
<body class="text-center eatery-background" >

    <div class="row">
        <div class="col-md-24">
            <h4 class="pad-bottom-50">
                I live in Southern Indiana and have worked in Louisville, KY for several years.<br />
                I enjoy the variety of foods available in Louisville and Southern Indiana and decided<br /> 
                that I would add this page as an additional opportunity to design and evolve a layout.
            </h4>
        </div>
    </div>
    <div class="row text-center">
        <table class="table-responsive table-bordered table-centered" style="margin:0 auto !important;float:none !important">
            <thead>
                <tr>
                    <th>Restaurant Name</th>
                    <th>Location</th>
                    <th>Phone</th>
                    <th>Expense</th>
                    <th>Menu Link</th>
                </tr>
            </thead>
            <tbody>
                @{foreach (var eatery in Model)
                {
                    <tr>
                        <td>@eatery.Name</td>
                        <td>@eatery.Location</td>
                        <td>@eatery.Phone</td>
                        <td>@eatery.ExpenseLevel</td>
                        <td>@eatery.MenuWebSite</td>
                    </tr>
                    }
                }

            </tbody>
        </table>
    </div>
    <br /><br /><br /><br />
    
</body>

    


ben-pister.WebUI/Views/MathGame/Balloons.cshtml

@{
    ViewBag.Title = "Balloons";
}
<body class="balloon-game-background">
    <div class="col-md-2 no-margin" style="height:50px">
        <button id="startBalloonGame" class="btn btn-success">Begin Game</button>
    </div>

    <div class="col-md-10 no-margin">
        <canvas id="balloonCanvas" class="no-margin" width="1100" height="700"></canvas>
    </div>
</body>



ben-pister.WebUI/Views/Resume/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="col-md-3"></div>
<div class="col-md-6" style="text-align:center;height:100%">
    <div id="resume_window" class="hidden-md hidden-sm resume-initial text-center">
        <object id="embed-resume" class="text-center" type="application/pdf" data="/Doc_Resources/Ben Pister Resume_1.pdf" width="800" height="950"></object>
    </div>
</div>
<div class="col-md-3"></div>

ben-pister.WebUI/Views/Shared/TopNavigation.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    @Html.ActionLink("Ben Pister - Software Developer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
</div>

ben-pister.WebUI/Views/Shared/_Analytics.cshtml
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87362496-1', 'auto');
  ga('send', 'pageview');

</script>

ben-pister.WebUI/Views/Shared/_FooterViewShared.cshtml
<div class="foregnd">
    I am a very motivated, eager to learn developer currently working with the .NET platform
</div>

ben-pister.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ben Pister - Software Developer</title>
    @Styles.Render("~/Content/css")
    
</head>
<body>
    <div>
        @Html.Partial("_TopNavigation")
    </div>

    <div>
        @RenderBody()
    </div>

    <div class="hidden-xs navbar navbar-fixed-bottom">
        <footer class="my_footer">
            @Html.Partial("_FooterViewShared")
            @Html.Partial("_Analytics")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
</body>
</html>

ben-pister.WebUI/Views/Shared/_MathGameInstructions.cshtml
<table id="gamePlayInstructions" class="table-responsive table-bordered table-striped level-instruction-table">
    <thead>
        <tr>
            <td><strong>Game Play Instructions</strong></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                The goal of this "game" is for individuals to solve as many math problems as possible in 5 minutes (300 seconds).<br />
                It is, of course, not possible to restrict calculators but I do encourage people to challenge themselves
                to use their great built-in computer, the human brain (on paper if needed, of course). <br />
            </td>
        </tr>
        <tr>
            <td>
                Once a level is selected, this will be the level for the duration of the 5 minutes. <br />
                If another level is desired, there is a "Reset Game" button at the bottom of the page.<br />
                I have attempted to adjust scoring to the difficulty level of both level selection and
                mathematical operation selected.
            </td>
        </tr>
        <tr>
            <td>
                <strong>When a game has ended, click or tap the "Reset Game" button to start a new game.</strong>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td>
                Three consecutive incorrect answers on one problem results in a 5 point score reduction with a minimum score of 0.<br />
                In this event, a calculation mode must be selected for another problem.
            </td>
        </tr>
    </tfoot>
</table>

ben-pister.WebUI/Views/Shared/_TopNavigation.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#hamburger-collapse">
                <span class="sr-only">Toggle nav</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="hamburger-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left center-align">
                <li class="btn-group-vertical"><a href="/Home/Index">Home</a></li>
                <li class="pad-left-15 pad-top-10">
                    <button id="linked-in-btn" class="black-link btn btn-default">LinkedIn</button>
                </li>
                
                <li class="visible-lg hidden-xs hidden-sm hidden-md pad-left-20 pad-top-10">
                    <button id="resume_link" class="black-link btn btn-default">View Resume</button>
                </li>

                <li class="hidden-lg pad-left-15 pad-top-10">
                    <button class="small-resume-button">
                        @Html.ActionLink("Download Resume", "PdfDownload", "FileDownload", null, new { @class = "download-link btn btn-default" })
                    </button>
                </li>
                <li class="pad-left-15 pad-top-10">
                    <button id="arithmeticGame" class="white-link btn btn-primary">Arithmetic Game</button>
                </li>
            </ul>
        </div>
    </div>
</nav>